version: "3"

services:
  mysql:
    restart: always
    image: mysql:latest
    container_name: my-sql-latest
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 33099:3306