logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss,SSS} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: ["beans"]

spring:
  main:
    banner-mode: console # console | off | log