 CREATE TABLE employee (
  id int NOT NULL AUTO_INCREMENT,
  email varchar(255) DEFAULT NULL,
  name varchar(255) DEFAULT NULL,
  salary varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)

CREATE TABLE `CUSTOMER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) NOT NULL,
  `MEMBERSHIP` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ADDRESS` (
  `CUSTOMER` INT NOT NULL,
  `BUILDING` VARCHAR(45) NOT NULL,
  `STREET` VARCHAR(100) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `ZIPCODE` VARCHAR(45) NOT NULL,
   CONSTRAINT `BK_PUB_ID_FK`
   FOREIGN KEY (`CUSTOMER`) REFERENCES `CUSTOMER` (`ID`)
);

CREATE TABLE `BRANCH` (
  `BRANCH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_SHORT_NAME` varchar(45) NOT NULL,
  `BRANCH_NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`BRANCH_ID`)
);


CREATE TABLE `STUDENT` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `CONTACT_NO` varchar(45) DEFAULT NULL,
  `BRANCH_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `BRANCH_ID_FK`
    FOREIGN KEY (`BRANCH_ID`)
    REFERENCES `BRANCH` (`BRANCH_ID`)
);

CREATE TABLE `BRANCHES` (
  `BRANCH_ID` int(11) NOT NULL AUTO_INCREMENT,
  `BRANCH_SHORT_NAME` varchar(45) NOT NULL,
  `BRANCH_NAME` varchar(100) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`BRANCH_ID`)
);

CREATE TABLE `SUBJECT` (
  `SUBJECT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SUBJECT_NAME` varchar(100) NOT NULL,
  `SUBJECT_DESC` varchar(200) DEFAULT NULL,
  PRIMARY KEY (`SUBJECT_ID`)
);

CREATE TABLE `BRANCH_SUBJECT` (
  `BRANCH_ID` int(11),
  `SUBJECT_ID` int(11),
  PRIMARY KEY (`BRANCH_ID`,`SUBJECT_ID`),
  CONSTRAINT `BRANCH_SUB_ID_FK`
     FOREIGN KEY (`BRANCH_ID`)
     REFERENCES `BRANCHES` (`BRANCH_ID`),
  CONSTRAINT `SUBJECT_SUB_ID_FK`
     FOREIGN KEY (`SUBJECT_ID`)
     REFERENCES `SUBJECT` (`SUBJECT_ID`)
);

CREATE TABLE `USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `PASSWORD` VARCHAR(45) NOT NULL,
  `CREATED_TIME` DATETIME NOT NULL,
  `UPDATED_TIME` DATETIME NULL,
  `USER_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USER_NAME_UNIQUE` (`USER_NAME` ASC)
 );

CREATE TABLE `Contacts` (
  `ID` INT NOT NULL,  /* user id */
  `CONTACT_NO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`, `CONTACT_NO`)
 );

CREATE TABLE `Contact_Address` (
  `STREET` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `ZIP_CODE` VARCHAR(45) NOT NULL,
  `USER_ID` INT NOT NULL,
  `ADDR_TYPE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`USER_ID`, `ADDR_TYPE`)
 );

 CREATE TABLE `ADD` (
   `ID` INT NOT NULL AUTO_INCREMENT,
   `CONTACT_NO` INT NOT NULL AUTO_INCREMENT,
   PRIMARY KEY (`ID`, `CONTACT_NO`)
  );